version: '3.8'

services:
  # RPC Server Test (standalone)
  verus-rpc-server-test:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    container_name: verus-rpc-server-standalone
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../../config:/app/config:ro
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=0
      - DEVELOPMENT_MODE=false
      - ENABLE_SECURITY_HEADERS=true
    networks:
      - test-network
    command: ["sh", "-c", "cp /app/config/Conf.toml . && verus-rpc-server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "User-Agent: Docker-Health-Check", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache
  redis-test:
    image: redis:7-alpine
    container_name: verus-redis-standalone
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - test-network
    command: redis-server --bind 0.0.0.0 --protected-mode yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  test-network:
    driver: bridge
